//! macOS adapter: AppKit change notifications via changeCount, Keychain-backed
//! storage (mac_crypto), and guarded Command+V through CoreGraphics.
use crate::model::*;
use objc::{class, msg_send, runtime::Object, sel, sel_impl};
use std::{
    sync::mpsc::{self, Receiver},
    time::Duration,
};

#[link(name = "AppKit", kind = "framework")]
unsafe extern "C" {}
#[link(name = "ApplicationServices", kind = "framework")]
unsafe extern "C" {
    fn AXIsProcessTrusted() -> bool;
    fn CGEventCreateKeyboardEvent(
        source: *const std::ffi::c_void,
        key: u16,
        down: bool,
    ) -> *mut std::ffi::c_void;
    fn CGEventSetFlags(event: *mut std::ffi::c_void, flags: u64);
    fn CGEventPost(tap: u32, event: *mut std::ffi::c_void);
    fn CGEventSourceKeyState(state: i32, key: u16) -> bool;
}
#[link(name = "CoreFoundation", kind = "framework")]
unsafe extern "C" {
    fn CFRelease(object: *const std::ffi::c_void);
}

unsafe fn ns(text: &str) -> *mut Object {
    let allocated: *mut Object = unsafe { msg_send![class!(NSString), alloc] };
    let string: *mut Object = unsafe {
        msg_send![allocated,initWithBytes:text.as_ptr() length:text.len() encoding:4usize]
    };
    unsafe { msg_send![string, autorelease] }
}
unsafe fn string(value: *mut Object) -> String {
    if value.is_null() {
        return String::new();
    }
    let ptr: *const std::ffi::c_char = unsafe { msg_send![value, UTF8String] };
    if ptr.is_null() {
        String::new()
    } else {
        unsafe { std::ffi::CStr::from_ptr(ptr) }
            .to_string_lossy()
            .into_owned()
    }
}
fn with_pool<T>(f: impl FnOnce() -> T) -> T {
    unsafe {
        let pool: *mut Object = msg_send![class!(NSAutoreleasePool), new];
        let value = f();
        let _: () = msg_send![pool, drain];
        value
    }
}
fn change_count() -> isize {
    with_pool(|| unsafe {
        let board: *mut Object = msg_send![class!(NSPasteboard), generalPasteboard];
        msg_send![board, changeCount]
    })
}
pub fn subscribe() -> Result<Receiver<()>, String> {
    let (tx, rx) = mpsc::channel();
    std::thread::spawn(move || {
        let mut last = change_count();
        loop {
            std::thread::sleep(Duration::from_millis(500));
            let current = change_count();
            if last != current {
                last = current;
                if tx.send(()).is_err() {
                    break;
                }
            }
        }
    });
    Ok(rx)
}
pub fn foreground() -> usize {
    with_pool(|| unsafe {
        let workspace: *mut Object = msg_send![class!(NSWorkspace), sharedWorkspace];
        let app: *mut Object = msg_send![workspace, frontmostApplication];
        if app.is_null() {
            0
        } else {
            let pid: i32 = msg_send![app, processIdentifier];
            pid as usize
        }
    })
}
pub fn valid_target(target: usize, own: usize) -> bool {
    target != 0 && target != own && target != std::process::id() as usize
}
pub fn activate(target: usize) -> bool {
    with_pool(|| unsafe {
        let app: *mut Object = msg_send![class!(NSRunningApplication),runningApplicationWithProcessIdentifier:target as i32];
        if app.is_null() {
            false
        } else {
            let ok: bool = msg_send![app,activateWithOptions:2usize];
            ok
        }
    })
}
pub fn read(settings: &Settings) -> Result<Option<Captured>, String> {
    let blocked = with_pool(|| unsafe {
        let board: *mut Object = msg_send![class!(NSPasteboard), generalPasteboard];
        let types: *mut Object = msg_send![board, types];
        [
            "local.clibo.internal",
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
        ]
        .iter()
        .any(|t| {
            let has: bool = msg_send![types,containsObject:ns(t)];
            has
        })
    });
    if blocked {
        return Ok(None);
    }
    let source = with_pool(|| unsafe {
        let workspace: *mut Object = msg_send![class!(NSWorkspace), sharedWorkspace];
        let app: *mut Object = msg_send![workspace, frontmostApplication];
        let name: *mut Object = msg_send![app, bundleIdentifier];
        string(name)
    });
    if settings
        .excluded_apps
        .iter()
        .any(|s| s.eq_ignore_ascii_case(&source))
    {
        return Ok(None);
    }
    let mut clipboard = arboard::Clipboard::new().map_err(|e| e.to_string())?;
    if let Ok(text) = clipboard.get_text() {
        if text.is_empty() {
            return Ok(None);
        }
        if text.len() > MAX_TEXT {
            return Err("文字超过 1 MiB，已跳过".into());
        }
        if settings.detect_sensitive && is_sensitive(&text) {
            return Ok(None);
        }
        return Ok(Some(Captured {
            text: Some(text),
            png: None,
            source,
        }));
    }
    if settings.capture_images {
        if let Ok(data) = clipboard.get_image() {
            if data.width.saturating_mul(data.height) > 25_000_000 {
                return Err("图片超过像素上限".into());
            }
            let img = image::RgbaImage::from_raw(
                data.width as u32,
                data.height as u32,
                data.bytes.into_owned(),
            )
            .ok_or("图片格式无效")?;
            let mut png = std::io::Cursor::new(Vec::new());
            image::DynamicImage::ImageRgba8(img)
                .write_to(&mut png, image::ImageFormat::Png)
                .map_err(|e| e.to_string())?;
            if png.get_ref().len() > MAX_IMAGE {
                return Err("图片超过 10 MiB，已跳过".into());
            }
            return Ok(Some(Captured {
                text: None,
                png: Some(png.into_inner()),
                source,
            }));
        }
    }
    Ok(None)
}
pub fn write(text: Option<&str>, png: Option<&[u8]>, _owner: usize) -> Result<(), String> {
    let mut clipboard = arboard::Clipboard::new().map_err(|e| e.to_string())?;
    if let Some(png) = png {
        let rgba = image::load_from_memory(png)
            .map_err(|e| e.to_string())?
            .into_rgba8();
        clipboard
            .set_image(arboard::ImageData {
                width: rgba.width() as usize,
                height: rgba.height() as usize,
                bytes: std::borrow::Cow::Owned(rgba.into_raw()),
            })
            .map_err(|e| e.to_string())?;
    } else if let Some(text) = text {
        clipboard.set_text(text).map_err(|e| e.to_string())?;
    } else {
        return Err("没有可复制的内容".into());
    }
    with_pool(|| unsafe {
        let board: *mut Object = msg_send![class!(NSPasteboard), generalPasteboard];
        let _: bool = msg_send![board,setString:ns("1") forType:ns("local.clibo.internal")];
    });
    Ok(())
}
pub fn paste(target: usize) -> Result<(), String> {
    unsafe {
        if !AXIsProcessTrusted() {
            return Err(
                "已复制；请在系统设置 → 隐私与安全性 → 辅助功能中允许 Clibo，再尝试自动粘贴".into(),
            );
        }
        let held = || {
            [36, 54, 55, 56, 58, 59, 60, 61, 62]
                .iter()
                .any(|key| CGEventSourceKeyState(1, *key))
        };
        for _ in 0..30 {
            if !held() {
                break;
            }
            std::thread::sleep(Duration::from_millis(10));
        }
        if foreground() != target || held() {
            return Err("已复制；目标焦点或按键状态变化，请手动粘贴".into());
        }
        let down = CGEventCreateKeyboardEvent(std::ptr::null(), 9, true);
        let up = CGEventCreateKeyboardEvent(std::ptr::null(), 9, false);
        if down.is_null() || up.is_null() {
            if !down.is_null() {
                CFRelease(down);
            }
            if !up.is_null() {
                CFRelease(up);
            }
            return Err("无法创建粘贴事件，请手动粘贴".into());
        }
        CGEventSetFlags(down, 1 << 20);
        CGEventSetFlags(up, 1 << 20);
        CGEventPost(0, down);
        CGEventPost(0, up);
        CFRelease(down);
        CFRelease(up);
    }
    Ok(())
}
